name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Install Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Android SDK Command Line Tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        sdkmanager --version
        sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"
        sdkmanager --licenses

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade Cython buildozer
        
    - name: Build APK
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libffi-dev libssl-dev
        sudo apt-get install -y autoconf automake libtool
        sudo apt-get install -y zlib1g-dev
        export ANDROID_NDK_HOME=$HOME/android-sdk/ndk/21.4.7075529
        export PATH=$PATH:$ANDROID_HOME/platform-tools
        buildozer android debug
