name: Build
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8.18
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0
          pip install cython==0.29.33
          pip install --upgrade wheel setuptools
          pip install python-for-android

      # Hapus step Clean Buildozer karena menyebabkan error

      - name: Initialize Buildozer
        run: |
          buildozer init
          # Edit buildozer.spec jika diperlukan
          sed -i 's/^android.sdk_path =.*/android.sdk_path = \/usr\/local\/lib\/android\/sdk/g' buildozer.spec
          sed -i 's/^android.ndk_path =.*/android.ndk_path = \/usr\/local\/lib\/android\/sdk\/ndk\/27.1.12297006/g' buildozer.spec

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libtool \
            pkg-config \
            autoconf \
            automake \
            python3-sphinx

      - name: Setup Android SDK & NDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-*_latest.zip
          rm commandlinetools-linux-*_latest.zip
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          mv cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

      - name: Create python-for-android directory
        run: |
          mkdir -p .buildozer/android/platform/
          cd .buildozer/android/platform/
          git clone https://github.com/kivy/python-for-android.git
          cd python-for-android
          python setup.py install

      - name: Build with Buildozer
        run: |
          buildozer android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
          retention-days: 90