name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Cache NDK
        id: cache-ndk
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer/android/platform/android-ndk-r25b
          key: ndk-cache-r25b

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            libffi-dev \
            libssl-dev \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            libunwind-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            libgstreamer1.0-dev \
            libgstreamer1.0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good

      - name: Download and Setup Android NDK
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.buildozer/android/platform
          cd ~/.buildozer/android/platform
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip
          rm android-ndk-r25b-linux.zip

      - name: Install Android SDK Command Line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Setup Android SDK
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
          echo "ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade Cython==0.29.33
          pip install --upgrade buildozer==1.5.0
          pip install --upgrade virtualenv

      - name: Create and update buildozer.spec
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          sed -i 's/^android.ndk =.*/android.ndk = 25b/g' buildozer.spec
          sed -i 's/^android.sdk =.*/android.sdk = 33/g' buildozer.spec
          sed -i 's/^requirements =.*/requirements = python3==3.8.18,hostpython3==3.8.18,kivy,kivymd==1.1.1,pillow/g' buildozer.spec
          sed -i 's/^android.ndk_path =.*/android.ndk_path = ~/.buildozer\/android\/platform\/android-ndk-r25b/g' buildozer.spec

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
